# Generated by Django 4.0.4 on 2022-05-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='text_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='example',
            name='text_ru',
            field=models.TextField(max_length=200, null=True, verbose_name='Текст'),
        ),
    ]
